// GENERATED by scripts/export_spec.py in the Sol repo. Do not edit.
//
// Sol's numbers used to live in three places (this file's hardcoded
// ancestor, sol.mdx, and the Sol repo's YAML) and drifted apart: this
// component claimed an RTX 2070 Super, float16, n_embd 512 and a target
// perplexity of 15-25 long after all four were false. Regenerate with
//   python -m scripts.export_spec
// and copy the output here. tests/test_spec_drift.py enforces freshness.

export const solSpec = {
    "_generated_by": "scripts/export_spec.py \u2014 do not edit by hand",
    "name": "micro_50m_8gb",
    "params": 52901712,
    "hardware": {
      "gpu": "NVIDIA GeForce RTX 4070 Laptop GPU",
      "architecture": "Ada Lovelace (sm_89)",
      "vram_gb": 8,
      "note": "An earlier spec targeted an RTX 2070 Super and float16. Wrong machine \u2014 see AGENTS.md.",
    },
    "architecture": {
      "n_layer": 8,
      "n_head": 8,
      "n_embd": 592,
      "head_dim": 74,
      "block_size": 512,
      "vocab_size": 32000,
      "bias": false,
      "dropout": 0.0,
      "weight_tying": true,
    },
    "training": {
      "batch_size": 4,
      "gradient_accumulation_steps": 16,
      "tokens_per_step": 32768,
      "max_iters": 40000,
      "total_train_tokens": 1310720000,
      "epochs": 3.66,
      "learning_rate": 0.0003,
      "min_lr": 3e-05,
      "warmup_iters": 1000,
      "weight_decay": 0.1,
      "grad_clip": 1.0,
      "precision": "bfloat16",
      "gradient_checkpointing": false,
      "seed": 42,
      "wall_clock_hours": 30.3,
      "training_hours": 16.9,
      "asleep_hours": 12.17,
      "throughput_tokens_per_second": 20067,
      "peak_vram_mib": 2344,
    },
    "data": {
      "dataset": "roneneldan/TinyStories",
      "train_docs": 1748358,
      "train_tokens": 357852786,
      "val_docs": 15141,
      "val_tokens": 2956183,
      "train_exact_dup_rate": 0.1458,
      "val_cross_split_leakage_dropped": 6304,
      "vocab_size": 32000,
      "max_train_tokens": 357852786,
    },
    "evaluation": {
      "n_val_docs": 15141,
      "n_val_tokens": 2955739,
      "n_boot": 10000,
      "perplexity": 3.719,
      "ci_lo": 3.693,
      "ci_hi": 3.745,
      "baselines": {
        "trigram": 23.4,
        "unigram": 379.0,
        "uniform": 32000.0,
      },
      "rubric": {
        "n": 60,
        "grammar": 4.0,
        "coherence": 3.15,
        "on_topic_in_domain": 5.0,
        "on_topic_out_of_domain": 1.47,
        "repetition": 3.98,
      },
    },
    "ablations": {
      "budget_iters": 8000,
      "seed_variance_sd": 0.0045,
      "seed_variance_mean": 4.49,
      "learning_rate": {
        "1e-4": 5.38,
        "3e-4": 4.489,
        "1e-3": 4.162,
      },
      "data_scale": {
        "100m": 4.572,
        "full": 4.489,
      },
    },
    "deployment": {
      "live_url": "https://sol-52m.streamlit.app",
      "weights_url": "https://huggingface.co/SpicyGuac/sol-001",
      "repo_url": "https://github.com/ArepaMan/sol",
      "host": "Streamlit Community Cloud (free tier)",
      "host_ram_limit_mb": 1024,
      "model_load_seconds": 6.7,
      "tokens_per_second_deployed": 16.0,
      "tokens_per_second_local_cpu": 24.6,
      "tokens_per_second_local_gpu": 90.0,
      "bundle_mib": 103.1,
    },
  } as const;

export type SolSpec = typeof solSpec;
